import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

import { SideBar } from "~/components/sidebar";
import { Article } from "~/components/article";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Blake Savage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <SideBar />
        </div>
        <div className="flex h-screen justify-center">
          <div className="h-screen w-full pt-2 md:max-w-3xl">
            <Article path="articles/contact.md"/>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
