import { type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import { Toaster } from "react-hot-toast";
import Head from "next/head";
import { useState } from "react";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  const [darkToggle, setDarkToggle] = useState(true)

  return (
    <SessionProvider session={session}>
      <Head>
        <title>Blake Savage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster />
      <div className={`relative ${darkToggle ? 'dark' : 'light'}`}>
        <button className={`z-40 absolute md:fixed right-2 top-14 md:left-14 md:top-auto md:bottom-8 rounded-full w-16 h-16 md:w-20 md:h-20 text-s md:text-base ${!darkToggle ? 'bg-slate-800 text-white' : ''} ${darkToggle ? 'bg-slate-200 text-slate-800' : ''}`} onClick={() => setDarkToggle(!darkToggle)}>
          <div className="justify-center items-center">
            {darkToggle ?
              "Light"
              :
              "Dark"
            }
          </div>
        </button>
        <Component {...pageProps} />
      </div>
    </SessionProvider>
  );
};


export default api.withTRPC(MyApp);
