import { type NextPage } from "next";
import Head from "next/head";

const SinglePostPage: NextPage = () => {

        // <link rel="icon" href="/favicon.ico" />
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>
          Post Page
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;
