import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

import { SideBar } from "~/components/sidebar";
import { Article } from "~/components/article";
import Link from "next/link";

const ProjectCard = (props: {name: string, link?: string}) => {
  return (
    <div className="w-80 rounded-lg flex bg-white">
      <div className="text-xl font-bold text-slate-600 p-4">
        {props.name}
      </div>
    </div>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Blake Savage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex h-screen w-full">
          <div className="me-80">
            <SideBar />
          </div>
            <div className="h-screen w-full pt-2 md:max-w-4xl">
              <h1 className="ms-4">Projects</h1>
              <ProjectCard name="Onionskin Studio"/>
            </div>
        </div>
      </main>
    </>
  );
};

export default Home;
